language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
before_script:
  - npm install -g bower
  - which bower
  - mvn install -f frontend-ui/pom.xml -Dgpg.skip=true
  - mvn install -f backend-ui/pom.xml -Dgpg.skip=true
script:
  - mvn test -f backend-api/pom.xml