language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
before_script:
  - npm install -g bower
  - which bower
  - mvn install -f frontend-ui-backbonejs/pom.xml -Dgpg.skip=true
  - npm install -g gulp
  - pushd frontend-ui-reactjs
  - npm install
  - popd
  - mvn install -f frontend-ui-reactjs/pom.xml -Dgpg.skip=true
  - mvn install -f backend-ui/pom.xml -Dgpg.skip=true
script:
  - mvn test -f backend-api/pom.xml
